language: python
python:
  - "3.6.3"

#Django & Database
addons:
  #Travis CI does not yet support Postgres 10.1
  #See https://github.com/travis-ci/travis-ci/issues/8537
  #postgresql: "10.1"
  postgresql: "9.4"

sudo: false

env:
  -DJANGO=2.1 DB=mysql
  -DJANGO=2.1 DB=sqlite3
  -DJANGO=2.1 DB=postgresql

install:
  - pip install -r requirements.txt
  - pip install coveralls


#mysql db creation
before_script:
  - sleep 15
  - psql -c 'create database test;' -U postgres

# command to run tests
script:
  - python test_runner.py test
  - coverage run --source=django_blog_it.posts,django_blog_it.django_blog_it test_runner.py test

after_success:
  coveralls
