# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog_it', '0011_auto_20160718_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True, max_length=160, null=True),
        ),
    ]
