# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog_it', '0010_theme'),
        ('django_blog_it', '0014_auto_20160719_0618'),
    ]

    operations = [
    ]
