# Generated by Django 2.1 on 2020-03-20 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog_it', '0015_auto_20180304_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
