# Generated by Django 2.1 on 2020-03-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog_it', '0016_auto_20200320_1551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUsSettings',
        ),
    ]
