# Generated by Django 2.1 on 2020-03-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog_it', '0017_delete_contactussettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='editor_type',
            field=models.CharField(choices=[('ckeditor', 'CKEditor'), ('tinymce', 'TinyMCE')], default='ckeditor', max_length=10),
        ),
    ]
